const products = [
  {
    id: 1,
    titleFa: 'گوشی موبایل اپل iPhone 17 Pro ZA/A ظرفیت 256 گیگابایت رم 12 گیگابایت',
    titleEn: 'Apple iPhone 17 Pro ZA/A 256/12GB - Not Active',
    category: 'گوشی موبایل',
    imageSrc: './assets/images/products-image/01.webp',
    price: 360_000_000,
    discount: 5,
    stock: 3,
    orderLimit: 1,
    rating: 3.2,
    details: {
      colors: ['نارنجی', 'نقره ای'],
    },
  },

  {
    id: 2,
    titleFa: 'هدفون بی سیم انکر مدل Soundcore Q20i A3004',
    titleEn: 'Anker Soundcore Q20i A3004 Wireless Headphone',
    category: 'هندزفری، هدفون، هدست',
    imageSrc: './assets/images/products-image/02.webp',
    price: 6_800_000,
    discount: 15,
    stock: 4,
    orderLimit: 2,
    rating: 4.3,
    details: {
      colors: ['سفید', 'مشکی', 'آبی'],
    },
  },

  {
    id: 3,
    titleFa: 'گوشی موبایل اپل مد‌ل iPhone 17 CH/A ظرفیت 256 گیگابایت رم 8 گیگابایت',
    titleEn: 'Apple iPhone 17 256/8GB CH/A - Not Active',
    category: 'گوشی موبایل',
    imageSrc: './assets/images/products-image/03.webp',
    price: 230_000_000,
    discount: 5,
    stock: 5,
    orderLimit: 1,
    rating: 4.2,
    details: {
      colors: ['سفید', 'سبز', 'بنفش', 'آبی', 'مشکی'],
    },
  },

  {
    id: 4,
    titleFa: 'هندزفری بلوتوثی کیو سی وای مدل T13 ANC 2',
    titleEn: 'QCY T13 ANC 2 Bluetooth Earphones',
    category: 'هندزفری، هدفون، هدست',
    imageSrc: './assets/images/products-image/04.webp',
    price: 1_980_000,
    discount: 0,
    stock: 5,
    orderLimit: 4,
    rating: 4.5,
    details: {
      colors: ['سفیذ', 'سرمه ای', 'مشکی'],
    },
  },

  {
    id: 5,
    titleFa: 'مودم روتر VDSL/ADSL تی پی-لینک مدل TD-W9950',
    titleEn: 'TD-W9950 300Mbps Wireless N VDSL/ADSL Modem Router',
    category: 'مودم',
    imageSrc: './assets/images/products-image/05.webp',
    price: 4_200_000,
    discount: 0,
    stock: 12,
    orderLimit: 5,
    rating: 4.3,
    details: {
      colors: ['طوسی'],
    },
  },
  {
    id: 6,
    titleFa: 'هندزفری بلوتوثی اپل مدل AirPods Pro 3',
    titleEn: 'Apple AirPods Pro 3 Wireless Handsfree',
    category: 'هندزفری، هدفون، هدست',
    imageSrc: './assets/images/products-image/06.webp',
    price: 40_500_000,
    discount: 5,
    stock: 10,
    orderLimit: 4,
    rating: 4.6,
    details: {
      colors: ['سفید'],
    },
  },

  {
    id: 7,
    titleFa: 'پارتی باکس جی بی ال مدل partybox Stage 320',
    titleEn: 'JBL partybox Stage 320 Portable Bluetooth Speaker',
    category: 'اسپیکر',
    imageSrc: './assets/images/products-image/07.webp',
    price: 63_450_000,
    discount: 5,
    stock: 4,
    orderLimit: 2,
    rating: 4.5,
    details: {
      colors: ['مشکی', '', ''],
    },
    isAvailable: true,
  },

  {
    id: 8,
    titleFa: 'گوشی موبایل اپل iPhone 17 Pro Max ZA/A ظرفیت 256 گیگابایت رم 12 گیگابایت',
    titleEn: 'Apple iPhone 17 Pro Max ZA/A 256/12GB - Not Active',
    category: 'گوشی موبایل',
    imageSrc: './assets/images/products-image/08.webp',
    price: 339_099_000,
    discount: 0,
    stock: 1,
    orderLimit: 1,
    rating: 3.8,
    details: {
      colors: ['آبی تیره', 'نارنجی'],
    },
  },

  {
    id: 9,
    titleFa: 'اسپیکر بلوتوثی خانگی هارمن کاردن مدل Aura Studio 4',
    titleEn: 'Harman Kardon aura studio 4 bluetooth speaker',
    category: 'اسپیکر',
    imageSrc: './assets/images/products-image/09.webp',
    price: 43_500_000,
    discount: 0,
    stock: 8,
    orderLimit: 3,
    rating: 4.4,
    details: {
      colors: ['مشکی', '', ''],
    },
  },

  {
    id: 10,
    titleFa: 'گوشی موبایل سامسونگ Galaxy S25 Ultra 5G ظرفیت 512 گیگابایت رم 12 گیگابایت - ویتنام',
    titleEn: 'Samsung Galaxy S25 Ultra 512/12GB - Vietnam',
    category: 'گوشی موبایل',
    imageSrc: './assets/images/products-image/10.webp',
    price: 250_000_000,
    discount: 2,
    stock: 1,
    orderLimit: 1,
    rating: 4.4,
    details: {
      colors: ['', '', ''],
    },
  },

  {
    id: 11,
    titleFa: 'لپ تاپ ایسوس 15.6 اینچی مدل Vivobook 15 X1504VA ',
    titleEn: 'ASUS VivoBook 15 X1504VA i3 1315U 8GB RAM 512GB SSD UHD Graphics',
    category: 'لپ تاپ',
    imageSrc: './assets/images/products-image/11.webp',
    price: 69_500_000,
    discount: 0,
    stock: 8,
    orderLimit: 1,
    rating: 4.1,
    details: {
      colors: ['سرمه ای', 'بژ'],
    },
  },

  {
    id: 12,
    titleFa: 'هدفون بی سیم کیو سی وای مدل H3',
    titleEn: 'QCY H3 Wireless headphone',
    category: 'هندزفری، هدفون، هدست',
    imageSrc: './assets/images/products-image/12.webp',
    price: 6_800_000,
    discount: 10,
    stock: 2,
    orderLimit: 2,
    rating: 4.1,
    details: {
      colors: ['سفید', 'مشکی', 'سرمه ای'],
    },
  },

  {
    id: 13,
    titleFa: 'لپ تاپ 15.6 اینچی لنوو مدل IdeaPad 1 15IJL7 Celeron',
    titleEn: 'Lenovo IdeaPad 1 15IJL7 Celeron N4500 8GB 256GB 15.6 inch Laptop',
    category: 'لپ تاپ',
    imageSrc: './assets/images/products-image/13.webp',
    price: 42_400_000,
    discount: 0,
    stock: 5,
    orderLimit: 1,
    rating: 4.6,
    details: {
      colors: ['خاکستری'],
    },
  },

  {
    id: 14,
    titleFa: 'اسپیکر بلوتوثی قابل حمل جی بی ال مدل Clip 5',
    titleEn: 'JBL Clip 5 portable Bluetooth speaker',
    category: 'اسپیکر',
    imageSrc: './assets/images/products-image/14.webp',
    price: 6_800_000,
    discount: 0,
    stock: 10,
    orderLimit: 2,
    rating: 4.7,
    details: {
      colors: ['مشکی', 'سفیذ', 'بنفش', 'سرمه ای'],
    },
  },

  {
    id: 15,
    titleFa: 'لپ تاپ اچ پی 15.6 اینچی مدل Victus 15 FA2082WM',
    titleEn: 'HP Victus 15 FA2082WM i5 13420H 16GB RAM 512GB SSD RTX4050',
    category: 'لپ تاپ',
    imageSrc: './assets/images/products-image/15.webp',
    price: 119_900_000,
    discount: 15,
    stock: 3,
    orderLimit: 1,
    rating: 3.6,
    details: {
      colors: ['خاکستری'],
    },
  },

  {
    id: 16,
    titleFa: 'مودم روتر VDSL/ADSL تی پی-لینک مدل Archer VR300',
    titleEn: 'TP-LINK VDSL/ADSL Archer VR300 Modem Router',
    category: 'مودم',
    imageSrc: './assets/images/products-image/16.webp',
    price: 1_000_000,
    discount: 0,
    stock: 7,
    orderLimit: 3,
    rating: 4.4,
    details: {
      colors: ['مشکی'],
    },
  },

  {
    id: 17,
    titleFa: 'هندزفری بی سیم انکر مدل Soundcore R50i',
    titleEn: 'Anker Soundcore R50i bluetooth Earbuds',
    category: 'هندزفری، هدفون، هدست',
    imageSrc: './assets/images/products-image/17.webp',
    price: 2_290_000,
    discount: 0,
    stock: 3,
    orderLimit: 3,
    rating: 4.6,
    details: {
      colors: ['مشکی'],
    },
  },

  {
    id: 18,
    titleFa: 'اسپیکر بلوتوثی قابل حمل جی بی ال مدل Charge 6',
    titleEn: 'JBL Charge 6 Portable Bluetooth Speaker',
    category: 'اسپیکر',
    imageSrc: './assets/images/products-image/18.webp',
    price: 24_900_000,
    discount: 10,
    stock: 10,
    orderLimit: 2,
    rating: 4.6,
    details: {
      colors: ['صورتی', 'قرمز', 'مشکی'],
    },
  },
];
